class Config:
    SECRET_KEY="LJHGFDCVBJKIU87654REWESAZXKJHGTFDFTYUOIUGV"
    SQLALCHEMY_DATABASE_URI = "sqlite:///reminders.db"
    SQLALCHEMY_TRACK_MODIFICATIONS=False
    JWT_SECRET_KEY=SECRET_KEY
